CREATE TABLE Topic (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    author_id BIGINT REFERENCES User(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES Course(id) ON DELETE CASCADE
);