CREATE TABLE responses (
    id BIGSERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    author_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    is_solution BOOLEAN DEFAULT FALSE
);