CREATE TABLE Response (
    id BIGSERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    topic_id BIGINT REFERENCES Topic(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    author_id BIGINT REFERENCES User(id) ON DELETE CASCADE,
    is_solution BOOLEAN DEFAULT FALSE
);